// @ts-check
// Renders a probe run as markdown. Pure. The output is the input for a human-written
// research/live/FINDINGS.md (PLAN.md §9 Phase 0b exit), not a replacement for it.

/**
 * @typedef {{ id: string, title: string, status: 'ok' | 'error' | 'skipped', reason?: string,
 *   checks: { name: string, result: string, detail?: string }[], observations: Record<string, unknown>, exchanges: number }} TestResult
 */

const ICON = /** @type {Record<string, string>} */ ({ pass: 'PASS', fail: 'FAIL', info: 'info', unknown: '??', skip: 'skip' });

/** @param {string} s */
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');

/**
 * @param {{ alias: string, runId: string, startedAt: string, finishedAt: string, apiVia: string,
 *   models: Record<string, { id: string, token_conversion_rate?: any } | null>, options: Record<string, unknown>,
 *   budget: { before: any, after: any } | null, spentEstimate: number, maxSpend: number,
 *   results: TestResult[], measurements: any[], usageFields: Record<string, any>,
 *   servedModels: { requested: string, served: string, count: number }[], stoppedBy?: string | null }} run
 */
export function renderSummary(run) {
  const L = [];
  L.push(`# Phase 0b probe run: <${run.alias}>`, '');
  L.push(`Run \`${run.runId}\`, ${run.startedAt} to ${run.finishedAt}. Generated by \`phase0/probe/api-probe.mjs\`; fixtures are in the test folders next to this file.`, '');
  L.push('Everything below is raw observation. Confirm or correct PLAN.md in `research/live/FINDINGS.md`, citing fixture files.', '');
  if (run.stoppedBy) L.push(`**Run stopped early:** ${run.stoppedBy}`, '');

  L.push('## Models', '', '| Role | Model | Prompt rate | Completion rate |', '|---|---|---|---|');
  for (const [role, m] of Object.entries(run.models)) {
    if (!m) continue;
    L.push(`| ${role} | \`${m.id}\` | ${m.token_conversion_rate?.prompt ?? 'unpriced'} | ${m.token_conversion_rate?.completion ?? 'unpriced'} |`);
  }
  L.push('');

  L.push('## Budget', '');
  if (run.budget) {
    const b = run.budget;
    const used = b.after?.used != null && b.before?.used != null ? b.after.used - b.before.used : null;
    const left = b.after?.left != null && b.before?.left != null ? b.before.left - b.after.left : null;
    L.push(`- used counter: ${b.before?.used} → ${b.after?.used} (Δ ${used})`);
    L.push(`- remaining counter: ${b.before?.left} → ${b.after?.left} (Δ ${left})`);
  } else L.push('- not read (measurement off)');
  L.push(`- probe's own estimate (full price, get-models rates): ${Math.round(run.spentEstimate)} of the ${run.maxSpend} cap`, '');

  L.push('## Checks', '', '| Test | Check | Result | Detail |', '|---|---|---|---|');
  for (const r of run.results) {
    if (r.status !== 'ok') L.push(`| ${r.id} | (test) | ${r.status} | ${cell(r.reason || '')} |`);
    for (const c of r.checks) L.push(`| ${r.id} | ${cell(c.name)} | ${ICON[c.result] || c.result} | ${cell(c.detail || '')} |`);
  }
  L.push('');

  const t22 = run.results.find((r) => r.id === 'T22');
  const rows = /** @type {Record<string, any>[] | undefined} */ (t22?.observations.matrixRows);
  if (rows && rows.length) {
    L.push('## Model matrix (T22)', '', 'Multipliers are what the measured bill implies at the tokenizer\'s billed rates, after the +3 per-request constant (±0.05 on large prefixes).', '');
    L.push('| Model | Flavor | Served | Cache read | Read × | Write × | Tool call | Reasoning state | Round 2 with state | Round 2 without | Notes |', '|---|---|---|---|---|---|---|---|---|---|---|');
    const v = (/** @type {unknown} */ x) => (x === null || x === undefined ? '' : String(x));
    for (const r of rows) {
      const notes = [r.error, r.cacheError, r.thinking, r.reasoning, r.round2Placeholder ? `placeholder signature: ${r.round2Placeholder}` : ''].filter(Boolean).join('; ');
      L.push(`| \`${r.model}\` | ${r.flavor} | ${cell(v(r.served))} | ${r.cacheRead ?? ''}${r.cacheInput ? ` / ${r.cacheInput}` : ''} | ${v(r.readMult)} | ${v(r.writeMult)} | ${r.toolCall ? 'yes' : r.error ? '' : 'no'} | ${cell(v(r.state))} | ${cell(v(r.round2))} | ${cell(v(r.round2Without))} | ${cell(notes)} |`);
    }
    L.push('');
  }

  if (run.measurements.length) {
    L.push('## Budget deltas per measured step', '', '| Step | Measured Δ used | Δ remaining | Settled | First move (ms) | Est. discounted | Est. full | Est. ÷rate | Closest |', '|---|---|---|---|---|---|---|---|---|');
    for (const m of run.measurements) {
      L.push(`| ${cell(m.label)} | ${m.usedDelta} | ${m.leftDelta} | ${m.settled ? 'yes' : 'no'} | ${m.firstMoveMs ?? ''} | ${m.est?.discounted ?? ''} | ${m.est?.full ?? ''} | ${m.est?.inverse ?? ''} | ${m.closest ?? ''} |`);
    }
    L.push('');
  }

  const mism = run.servedModels.filter((s) => s.served && s.served !== s.requested);
  L.push('## Served model versus requested', '');
  if (!run.servedModels.length) L.push('No successful model responses.', '');
  else {
    L.push('| Requested | Served (response `model`) | Responses |', '|---|---|---|');
    for (const s of run.servedModels) L.push(`| \`${s.requested}\` | \`${s.served || '(none)'}\` | ${s.count} |`);
    L.push('', mism.length ? `${mism.length} pair(s) differ. Decide whether \`resolvedModel\` differences are aliases (harmless) or fallbacks (cache-health alarm, §3.5).` : 'All served ids match the requested ids.', '');
  }

  L.push('## T14: usage fields per flavor', '');
  for (const [k, v] of Object.entries(run.usageFields)) {
    L.push(`- **${k}** (${v.count} responses): ${v.fields.map((/** @type {string} */ f) => `\`${f}\``).join(', ')}`);
    for (const [c, cnt] of Object.entries(v.checks || {})) L.push(`  - **${c}**: ${cnt}`);
  }
  L.push('');

  L.push('## Observations per test', '');
  for (const r of run.results) {
    L.push(`### ${r.id}: ${r.title}`, '');
    L.push(`Status: ${r.status}${r.reason ? ` (${r.reason})` : ''}. Exchanges recorded: ${r.exchanges}.`, '');
    if (Object.keys(r.observations).length) L.push('```json', JSON.stringify(r.observations, null, 1), '```', '');
  }
  return L.join('\n');
}
